config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get "english" => "pages#english"

  match '/#contact',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nouveau message venant d'AuContraire!",
      :to => "pabfaust@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def english
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
	<%= yield %>

</body>
</html>

app/views/pages/anglais.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<nav class="navbar navbar-default navbar-fixed-top hidden-xs hidden-sm" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", :alt => "Au Contraire! Consulting", class:"img-responsive"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to anglais_path do %>
    <span class="glyphicon glyphicon-home"></span>
<% end %></li>
        <li><%= link_to "Expertise", root_path(anchor: "expertise") %></li>
        <li><%= link_to "References", root_path(anchor: "references") %></li>
        <li><%= link_to "Who are we ?", root_path(anchor: "qui sommes-nous") %></li>
        <li><%= link_to "Contact", root_path(anchor: "contact") %></li>
        <li><%= link_to image_tag("francais.png",), root_path %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <div class="media">
    <%= image_tag("intro.png", :alt => "Management interculturel", class:"img-responsive") %>
    </div>
  </div>

<div class="container-fluid", id="expertise">
  <div class="media">
    <%= image_tag("expertise.png", :alt => "Domaines d'expertise d'Au Contraire! Consulting", class:"img-responsive") %>
    </div>
  </div>

<div class="container-fluid", id="references">
  <div class="media">
    <%= image_tag("references.png", :alt => "Chinoise à chapeau rouge", class:"img-responsive") %>
    </div>
  </div>

<div class="container-fluid", id="qui sommes-nous">
  <div class="media">
    <%= image_tag("qui.png", :alt => "Eléonore Mandel", class:"img-responsive") %>
    </div>
  </div>


    <div class="container-fluid" id="contact">
      <div class="row spacer">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-envelope"></span> Mail<br>
        <a href="mailto:em@aucontraireconsulting.com">em@aucontraireconsulting.com</a>
    </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-phone"></span> Téléphone<br>
        +33 6 09 15 45 04</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-map-marker"></span> Adresse<br>
          <p>13 Rue Claude-Nicolas Ledoux<br>14970 Bénouville</p></div>
      </div>

    </div>
    

app/views/pages/english.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<nav class="navbar navbar-default navbar-fixed-top hidden-xs hidden-sm" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to image_tag("logo_en.png", :alt => "Au Contraire! Consulting", class:"img-responsive"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to english_path do %>
    <span class="glyphicon glyphicon-home"></span>
<% end %></li>
        <li><%= link_to "Expertise areas", english_path(anchor: "expertise_en") %></li>
        <li><%= link_to "References", english_path(anchor: "references_en") %></li>
        <li><%= link_to "About us", english_path(anchor: "about_us") %></li>
        <li><%= link_to "Contact us", english_path(anchor: "contact") %></li>
        <li><%= link_to "FRANCAIS", root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="english-xs visible-xs">
  <%= link_to image_tag("logo-xs.png", :alt => "Logo d'Au Contraire! Consulting"), root_path %>
  <%= link_to "FRANCAIS", root_path, class:"eng-xs" %>
  <%= link_to "About us", english_path(anchor: "about_us"), class:"qui-xs" %>
</div>

<div class="english-sm visible-sm">
  <%= link_to image_tag("logo_en.png", :alt => "Logo d'Au Contraire! Consulting"), root_path %>
  <%= link_to "FRANCAIS", english_path, class:"eng-sm" %>
  <%= link_to "About us", english_path(anchor: "about_us"), class:"qui-sm" %>
  <%= link_to "Expertise areas", english_path(anchor: "expertise_en"), class:"expertise-sm" %>
    <%= link_to root_path do %>
    <span class="home-sm glyphicon glyphicon-home"></span>
<% end %>
</div>

<div class="container-fluid">
  <div class="media">
    <%= image_tag("intro_en.png", :alt => "AuContraire! Constulting International", class:"img-responsive") %>
    </div>
  </div>

<div class="container-fluid", id="expertise_en">
  <div class="media">
    <%= image_tag("expertise_en.png", :alt => "Expertise areas of Au Contraire! Consulting", class:"img-responsive") %>
    </div>
  </div>

<div class="container-fluid", id="references_en">
  <div class="media">
    <%= image_tag("references_en.png", :alt => "Références d'AuContraire! Consulting", class:"img-responsive") %>
  </div>

<div class="container-fluid", id="about_us">
  <div class="media">
    <%= image_tag("about_us.png", :alt => "Eléonore Mandel", class:"img-responsive") %>
    </div>
  </div>


    <div class="container-fluid" id="contact">

          <div class="row spacer hidden-xs">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"></div>
       <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-plus-sign"></span> <a href="https://twitter.com/Prof_Mandel" alt="Twitter d'Eléonore Mandel"><%= image_tag("twitter.png", :alt => "Logo de Twitter") %></a><a href="http://www.viadeo.com/fr/profile/eleonore.mandel" alt="Profil Viadeo d'Eléonore Mandel"><%= image_tag("viameo.png", :alt => "Logo de Viadeo") %></a> <a href="https://www.linkedin.com/pub/eleonore-mandel/15/358/1a2" alt="Profil LinkedIn d'Eléonore Mandel"> 
      <%= image_tag("linkedin.png", :alt => "Logo de LinkedIn") %></a> <a href="http://www.doyoubuzz.com/eleonore-mandel" alt="Profil Doyoubuzz d'Eléonore Mandel">
      <%= image_tag("doyoubuzz.png", :alt => "Logo de Doyoubuzz") %></a></div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-20"></div>

    </div>

                 <div class="row spacer visible-xs">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-15"></div>
       <div class="col-lg-4 col-md-4 col-sm-4 col-xs-15"></div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-15">
        <a href="https://twitter.com/Prof_Mandel" alt="Twitter d'Eléonore Mandel"><%= image_tag("twitter-xs.png", :alt => "Logo de Twitter") %></a><a href="http://www.viadeo.com/fr/profile/eleonore.mandel" alt="Profil Viadeo d'Eléonore Mandel"><%= image_tag("viadeo-xs.png", :alt => "Logo de Viadeo") %></a> <a href="https://www.linkedin.com/pub/eleonore-mandel/15/358/1a2" alt="Profil LinkedIn d'Eléonore Mandel"> 
      <%= image_tag("linkedin-xs.png", :alt => "Logo de LinkedIn") %></a> <a href="http://www.doyoubuzz.com/eleonore-mandel" alt="Profil Doyoubuzz d'Eléonore Mandel">
      <%= image_tag("doyoubuzz-xs.png", :alt => "Logo de Doyoubuzz") %></a></div>
    </div>

      <div class="row spacer">

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><h3>CONTACT US</h3></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-envelope"></span> e-mail<br>
        <a href="mailto:em@aucontraireconsulting.com">em@aucontraireconsulting.com</a>
    </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-phone"></span> Mobile phone<br>
        +33 6 09 15 45 04</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-map-marker"></span> Address<br>
          <p>13 Rue Claude-Nicolas Ledoux<br>14970 Bénouville</p></div>
      </div>

    </div>

    <div class="footer">
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <a href="http://engagementperenne.fr/"><img src="http://img11.hostingpics.net/pics/555186footer.png" /></a>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <p class="mentions">N° SIRET Auto-entrepreneur : 80425515600015<br>Website hosted by : GANDI SAS, Joint-Stock company with a capital of 300,000€,<br>HQ address: 63-65 boulevard Massena à Paris (75013) FRANCE, registered under n°423 093 459 RCS PARIS<br>N° VAT FR81423093459 - Tel : +33.(0) 1 70.37.76.61 - Fax : +33.(0) 1 43 73 18 51</p>
        </div>
        <div class="hidden-xs visible-sm visible-md visible-lg col-sm-4 col-md-4 col-lg-4">
          <p class="signature">Design by Pablo Faust</p>
        </div>
    </div>
  </div>

app/views/pages/home.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<nav class="navbar navbar-default navbar-fixed-top hidden-xs hidden-sm" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", :alt => "Logo d'Au Contraire! Consulting", class:"img-responsive"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

      	<li><%= link_to root_path do %>
    <span class="glyphicon glyphicon-home"></span>
<% end %></li>
        <li><%= link_to "Domaines d'expertise", root_path(anchor: "expertise") %></li>
        <li><%= link_to "Références", root_path(anchor: "references") %></li>
        <li><%= link_to "Qui sommes-nous ?", root_path(anchor: "qui sommes-nous") %></li>
        <li><%= link_to "Contact", root_path(anchor: "contact") %></li>
        <li><%= link_to "ENGLISH", english_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="english-xs visible-xs">
  <%= link_to image_tag("logo-xs.png", :alt => "Logo d'Au Contraire! Consulting"), root_path %>
  <%= link_to "ENGLISH", english_path, class:"eng-xs" %>
  <%= link_to "Qui sommes-nous ?", root_path(anchor: "qui sommes-nous"), class:"qui-xs" %>
</div>

<div class="english-sm visible-sm">
  <%= link_to image_tag("logo.png", :alt => "Logo d'Au Contraire! Consulting"), root_path %>
  <%= link_to "ENGLISH", english_path, class:"eng-sm" %>
  <%= link_to "Qui sommes-nous ?", root_path(anchor: "qui sommes-nous"), class:"qui-sm" %>
  <%= link_to "Domaines d'expertise", root_path(anchor: "expertise"), class:"expertise-sm" %>
    <%= link_to root_path do %>
    <span class="home-sm glyphicon glyphicon-home"></span>
<% end %>
</div>

<div class="english-md visible-md">
  <%= link_to image_tag("logo.png", :alt => "Logo d'Au Contraire! Consulting"), root_path %>
  <%= link_to "ENGLISH", english_path %>
  <%= link_to "Qui sommes-nous ?", root_path(anchor: "qui sommes-nous") %>
  <%= link_to "Domaines d'expertise", root_path(anchor: "expertise") %>
    <%= link_to root_path do %>
    <span class="glyphicon glyphicon-home"></span>
<% end %>
</div>

<div class="container-fluid">
	<div class="media">
		<%= image_tag("intro.png", :alt => "AuContraire Consulting! International", class:"img-responsive") %>
		</div>
	</div>

<div class="container-fluid", id="expertise">
	<div class="media">
		<%= image_tag("expertise.png", :alt => "Domaines d'expertise d'Au Contraire! Consulting", class:"img-responsive") %>
		</div>
	</div>

<div class="container-fluid", id="references">
	<div class="media">
		<%= image_tag("references.png", :alt => "Références d'AuContraire! Consulting", class:"img-responsive") %>
		</div>
	</div>

<div class="container-fluid", id="qui sommes-nous">
	<div class="media">
		<%= image_tag("qui.png", :alt => "Eléonore Mandel", class:"img-responsive") %>
		</div>

	</div>


    <div class="container-fluid" id="contact">

      <div class="row spacer hidden-xs">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"></div>
       <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-plus-sign"></span> <a href="https://twitter.com/Prof_Mandel" alt="Twitter d'Eléonore Mandel"><%= image_tag("twitter.png", :alt => "Logo de Twitter") %></a><a href="http://www.viadeo.com/fr/profile/eleonore.mandel" alt="Profil Viadeo d'Eléonore Mandel"><%= image_tag("viameo.png", :alt => "Logo de Viadeo") %></a> <a href="https://www.linkedin.com/pub/eleonore-mandel/15/358/1a2" alt="Profil LinkedIn d'Eléonore Mandel"> 
      <%= image_tag("linkedin.png", :alt => "Logo de LinkedIn") %></a> <a href="http://www.doyoubuzz.com/eleonore-mandel" alt="Profil Doyoubuzz d'Eléonore Mandel">
      <%= image_tag("doyoubuzz.png", :alt => "Logo de Doyoubuzz") %></a></div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-20"></div>

    </div>

                 <div class="row spacer visible-xs">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-15"></div>
       <div class="col-lg-4 col-md-4 col-sm-4 col-xs-15"></div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-15">
        <a href="https://twitter.com/Prof_Mandel" alt="Twitter d'Eléonore Mandel"><%= image_tag("twitter-xs.png", :alt => "Logo de Twitter") %></a><a href="http://www.viadeo.com/fr/profile/eleonore.mandel" alt="Profil Viadeo d'Eléonore Mandel"><%= image_tag("viadeo-xs.png", :alt => "Logo de Viadeo") %></a> <a href="https://www.linkedin.com/pub/eleonore-mandel/15/358/1a2" alt="Profil LinkedIn d'Eléonore Mandel"> 
      <%= image_tag("linkedin-xs.png", :alt => "Logo de LinkedIn") %></a> <a href="http://www.doyoubuzz.com/eleonore-mandel" alt="Profil Doyoubuzz d'Eléonore Mandel">
      <%= image_tag("doyoubuzz-xs.png", :alt => "Logo de Doyoubuzz") %></a></div>
    </div>

      <div class="row spacer">

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><h3>CONTACT</h3></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-envelope"></span> Mail<br>
        <a href="mailto:em@aucontraireconsulting.com">em@aucontraireconsulting.com</a>
    </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-phone"></span> Téléphone<br>
        +33 6 09 15 45 04</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-20"><span class="glyphicon glyphicon-map-marker"></span> Adresse<br>
        	<p>13 Rue Claude-Nicolas Ledoux<br>14970 Bénouville</p></div>
      </div>

    </div>

    <div class="footer">
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <a href="http://engagementperenne.fr/"><img src="http://img11.hostingpics.net/pics/555186footer.png" /></a>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <p class="mentions">MENTIONS LEGALES : SIRET : 80425515600015<br>HEBERGEUR : GANDI SAS, société par Actions Simplifiée au capital de 300 000€, ayant son siège social au<br>63-65 boulevard Massena à Paris (75013) FRANCE, immatriculée sous le numéro 423 093 459 RCS PARIS<br>N° TVA FR81423093459 - Téléphone : +33.(0) 1 70.37.76.61 - Fax : +33.(0) 1 43 73 18 51</p>
        </div>
        <div class="hidden-xs visible-sm visible-md visible-lg col-sm-4 col-md-4 col-lg-4">
          <p class="signature">Design by Pablo Faust</p>
        </div>
    </div>
  </div>




    